use std::sync::Arc;

use bone_app::{
    AttentionItem, HistoryCursor, HistoryPage, RecentHistoryPage, RequestId, SessionId,
    SessionInfo, SessionView, SubmissionReceipt, SubmitInput, WorkspaceId,
};

use super::model::{DetailState, Focus, MainView, ModelRole, SecretText, SettingsData};
use crate::layout::HitTarget;

#[derive(Clone, Debug)]
pub enum Action {
    Noop,
    FocusNext,
    FocusPrevious,
    SelectPrevious,
    SelectNext,
    SelectSession(SessionId),
    Activate,
    Escape,
    Open(MainView),
    OpenDetail(DetailState),
    CloseDetail,
    Focus(Focus),
    MoveFocusedControl(isize),
    FocusVisibleControl(HitTarget),
    NewSession,
    BeginRenameSession(SessionId),
    SetSessionArchived {
        session: SessionId,
        archived: bool,
    },
    Input(char),
    Paste(String),
    Backspace,
    InsertNewline,
    Submit,
    SubmitFromActionBar,
    ScrollUp(usize),
    ScrollDown(usize),
    Stop,
    Quit,
    Terminate,
    BeginAcceptance {
        decision: bone_app::AcceptanceDecision,
        result: bone_app::ResultRef,
    },
    LoadOlderResults,
    LoadNewerResults,
    LoadOlderAcceptances,
    LoadNewerAcceptances,
    SelectSettingsProfile(usize),
    ConfigureModel(ModelRole),
    StartLogin,
    ConfigureCredential,
    Logout,
    OpenAttention(usize),
    BeginWriteResolution(bone_app::ExternalEffect),
    MoveAttention(isize),
    MoveWriteResolution(isize),
    RefreshWorkspaceChanges,
    LoadOlderWorkspaceChanges,
    LoadNewerWorkspaceChanges,
    MoveWorkspaceChange(isize),
    OpenWorkspaceChange(usize),
    CloseWorkspaceFile,
    LoadPreviousWorkspaceFile,
    LoadMoreWorkspaceFile,
    MoveWorkspaceFileControl(isize),
    RefreshArtifact,
    LoadOlderEvidence,
    LoadNewerEvidence,
    MoveEvidence(isize),
    OpenEvidence(usize),
    LoadPreviousEvidenceSource,
    LoadMoreEvidenceSource,
    CloseEvidenceSource,
}

#[derive(Clone, Debug)]
pub enum UiEvent {
    Action(Action),
    WorkspaceOpened {
        id: WorkspaceId,
        label: String,
        sessions: Vec<SessionInfo>,
        attention: Vec<AttentionItem>,
        attention_projection_pending: bool,
        unresolved_writes: Vec<bone_app::UnresolvedWriteView>,
    },
    SessionOpened {
        session: SessionId,
        generation: u64,
        snapshot: Arc<SessionView>,
        history: RecentHistoryPage,
    },
    SessionChanged {
        session: SessionId,
        generation: u64,
        snapshot: Arc<SessionView>,
    },
    HistoryLoaded {
        session: SessionId,
        generation: u64,
        page: HistoryPage,
    },
    OlderHistoryLoaded {
        session: SessionId,
        generation: u64,
        page: RecentHistoryPage,
    },
    RecentHistoryReloaded {
        session: SessionId,
        generation: u64,
        page: RecentHistoryPage,
    },
    RefreshOverviewRequested,
    PersistDraftsRequested,
    OverviewLoaded {
        generation: u64,
        sessions: Vec<SessionInfo>,
        attention: Vec<AttentionItem>,
        attention_projection_pending: bool,
        unresolved_writes: Vec<bone_app::UnresolvedWriteView>,
    },
    SettingsLoaded(Box<SettingsData>),
    ConfigUpdated {
        session: SessionId,
        generation: u64,
    },
    ConfigUpdateFailed {
        session: SessionId,
        generation: u64,
        message: String,
    },
    ConfigsReloaded {
        profile: bone_app::ProfileId,
        query: u64,
        failures: usize,
    },
    WriteResolved {
        session: SessionId,
        call: bone_app::CallRef,
    },
    WriteResolutionFailed {
        session: SessionId,
        call: bone_app::CallRef,
        message: String,
    },
    SessionReleased {
        generation: u64,
        receipt: bone_app::SessionReleaseReceipt,
    },
    LoginChanged {
        profile: bone_app::ProfileId,
        query: u64,
        state: bone_app::LoginState,
    },
    ResultsLoaded {
        session: SessionId,
        generation: u64,
        query: u64,
        page: bone_app::ResultPage,
    },
    OlderResultsLoaded {
        session: SessionId,
        generation: u64,
        query: u64,
        page: bone_app::ResultPage,
    },
    AcceptancesLoaded {
        session: SessionId,
        generation: u64,
        result: bone_app::ResultRef,
        query: u64,
        page: bone_app::AcceptancePage,
        append_older: bool,
    },
    AcceptanceSubmitted {
        session: SessionId,
        generation: u64,
        request_id: bone_app::AcceptanceRequestId,
        receipt: bone_app::AcceptanceReceipt,
    },
    AcceptanceFailed {
        session: SessionId,
        generation: u64,
        request_id: bone_app::AcceptanceRequestId,
        message: String,
    },
    WorkspaceChangesLoaded {
        workspace: WorkspaceId,
        query: u64,
        page: bone_app::WorkspaceChangePage,
        append: bool,
    },
    WorkspaceFileLoaded {
        workspace: WorkspaceId,
        query: u64,
        cursor: Option<bone_app::WorkspaceFileCursor>,
        append: bool,
        page: bone_app::WorkspaceFilePage,
    },
    WorkspaceChangesFailed {
        workspace: WorkspaceId,
        query: u64,
        message: String,
    },
    WorkspaceFileFailed {
        workspace: WorkspaceId,
        query: u64,
        path: String,
        source: bone_app::WorkspaceFileSource,
        cursor: Option<bone_app::WorkspaceFileCursor>,
        append: bool,
        message: String,
    },
    ArtifactLoaded {
        result: bone_app::ResultRef,
        query: u64,
        artifact: bone_app::ResultArtifact,
        evidence: bone_app::EvidencePage,
    },
    EvidenceLoaded {
        result: bone_app::ResultRef,
        query: u64,
        page: bone_app::EvidencePage,
    },
    EvidenceSourceLoaded {
        result: bone_app::ResultRef,
        query: u64,
        page: bone_app::EvidenceSourcePage,
        append: bool,
    },
    ArtifactFailed {
        result: bone_app::ResultRef,
        query: u64,
        message: String,
    },
    EvidenceSourceFailed {
        result: bone_app::ResultRef,
        query: u64,
        message: String,
    },
    ApiKeySaved {
        session: SessionId,
        generation: u64,
        profile: bone_app::ProfileId,
        reload_failures: usize,
    },
    ApiKeyFailed {
        session: SessionId,
        generation: u64,
        profile: bone_app::ProfileId,
        message: String,
    },
    DraftSaved {
        session: SessionId,
        generation: u64,
        revision: u64,
        text: String,
    },
    Submitted {
        session: SessionId,
        generation: u64,
        request_id: RequestId,
        receipt: SubmissionReceipt,
    },
    SessionCreated(SessionInfo),
    SessionRenamed {
        session: SessionId,
        generation: u64,
        operation: u64,
        title: String,
    },
    SessionArchived {
        session: SessionId,
        generation: u64,
        operation: u64,
        archived: bool,
    },
    SessionManagementFailed {
        session: SessionId,
        generation: u64,
        operation: u64,
        message: String,
    },
    OperationFailed {
        kind: OperationKind,
        session: Option<SessionId>,
        generation: Option<u64>,
        message: String,
    },
    Resized,
    Tick,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OperationKind {
    OpenSession,
    CreateSession,
    SaveDraft,
    Submit,
    Stop,
    LoadHistory,
    LoadOlderHistory,
    ReloadRecentHistory,
    RefreshOverview,
    LoadSettings,
    LoadResults,
    LoadOlderResults,
    LoadAcceptances,
    SubmitAcceptance,
    UpdateConfig,
    Login,
    Logout,
    ReleaseSession,
    RenameSession,
    ArchiveSession,
    ResolveWrite,
    LoadWorkspaceChanges,
    LoadWorkspaceFile,
    LoadArtifact,
    LoadEvidence,
    LoadEvidenceSource,
    SetApiKey,
}

#[derive(Clone, Debug)]
pub enum Effect {
    OpenSession {
        session: SessionId,
        generation: u64,
    },
    CreateSession {
        title: String,
    },
    RenameSession {
        session: SessionId,
        generation: u64,
        operation: u64,
        title: String,
    },
    ArchiveSession {
        session: SessionId,
        generation: u64,
        operation: u64,
        archived: bool,
    },
    SaveDraft {
        session: SessionId,
        generation: u64,
        revision: u64,
        text: String,
    },
    Submit {
        session: SessionId,
        generation: u64,
        input: SubmitInput,
    },
    Stop {
        session: SessionId,
        generation: u64,
    },
    LoadHistory {
        session: SessionId,
        generation: u64,
        after: bone_app::SessionSeq,
    },
    LoadOlderHistory {
        session: SessionId,
        generation: u64,
        cursor: HistoryCursor,
    },
    ReloadRecentHistory {
        session: SessionId,
        generation: u64,
    },
    RefreshOverview {
        generation: u64,
    },
    LoadSettings {
        session: SessionId,
        generation: u64,
        query: u64,
    },
    LoadResults {
        session: SessionId,
        generation: u64,
        query: u64,
    },
    LoadOlderResults {
        session: SessionId,
        generation: u64,
        query: u64,
        cursor: HistoryCursor,
    },
    LoadAcceptances {
        session: SessionId,
        generation: u64,
        result: bone_app::ResultRef,
        query: u64,
        cursor: Option<bone_app::AcceptanceCursor>,
        append_older: bool,
    },
    SubmitAcceptance {
        session: SessionId,
        generation: u64,
        submission: bone_app::AcceptanceSubmission,
    },
    UpdateConfig {
        session: SessionId,
        generation: u64,
        change: bone_app::ConfigChange,
    },
    StartLogin {
        profile: bone_app::ProfileId,
        query: u64,
    },
    Logout {
        profile: bone_app::ProfileId,
        query: u64,
    },
    SetApiKey {
        session: SessionId,
        generation: u64,
        profile: bone_app::ProfileId,
        key: SecretText,
    },
    ReloadOpenSessions {
        profile: bone_app::ProfileId,
        query: u64,
    },
    ReleaseSession {
        session: SessionId,
        generation: u64,
    },
    ResolveWrite {
        session: SessionId,
        call: bone_app::CallRef,
        resolution: bone_app::WriteResolution,
    },
    LoadWorkspaceChanges {
        workspace: WorkspaceId,
        query: u64,
        cursor: Option<bone_app::WorkspaceChangeCursor>,
        append: bool,
    },
    LoadWorkspaceFile {
        workspace: WorkspaceId,
        query: u64,
        path: String,
        source: bone_app::WorkspaceFileSource,
        cursor: Option<bone_app::WorkspaceFileCursor>,
        append: bool,
    },
    LoadArtifact {
        result: bone_app::ResultRef,
        query: u64,
    },
    LoadEvidence {
        result: bone_app::ResultRef,
        query: u64,
        cursor: bone_app::EvidenceCursor,
    },
    LoadEvidenceSource {
        result: bone_app::ResultRef,
        query: u64,
        source: bone_app::EvidenceRef,
        offset: u64,
        append: bool,
    },
    Shutdown,
}
